name: dash-crypto
dependencies:
  - python
  - pip
  - pip:
      - dash
      - plotly
      - requests
      - pandas
      - numpy 
      - scikit-learn 
      - matplotlib 
      - jupyter 
      - ipykernel 
      - "tensorflow[and-cuda]"
